name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out github repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
