name: Lint

on:
  push:
    branches:
      - 'main'
      - 'dev'
    pull_request:

jobs:
  files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint:check

  commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
